### ISSUE TITLE
Report On Missing Dependencies

### ISSUE THREAD

**Issue by ldo** [nasa/NASA-3D-Resources#14]
Many `.blend` files are missing external texture files. [Enclosed](https://github.com/nasa/NASA-3D-Resources/files/781987/missing_deps.txt) is a report generated according to

    for f in $(find . -name \*.blend  -not -exec ext-files --test-missing {} ';' -print); do
        echo
        echo "${f}:"
        ext-files --presence "$f"
    done

where the `ext-files` command comes from my [`render-useful`](https://github.com/ldo/render-useful) repo. Each “missing:” line reports the name of a missing file.

In total, 72 `.blend` files are missing 323 dependency files.

**Comment by ldo** [comment]
[Here](https://github.com/nasa/NASA-3D-Resources/files/931935/missing_deps.txt) is an updated report, against the latest version of the repo. The scanning command sequence has been revised to

    for f in $(find . -name \*.blend  -not -exec $ext_files --test-missing {} ';' -print); do
        echo
        echo "${f}:"
        $ext_files --presence "$f" | grep -v '^present\:'
    done

to omit mentioning dependencies that are present, only ones that are missing.

The total is now 71 `.blend` files missing 332 dependency files.

**Comment by ldo** [comment]
[Here](https://github.com/nasa/NASA-3D-Resources/files/2711934/missing_deps.txt) is an updated report, now showing 83 `.blend` files missing 299 dependency files.

**Comment by ldo** [comment]
[Here](https://github.com/nasa/NASA-3D-Resources/files/4063665/missing_deps.txt) is an updated report, now showing 81 `.blend` files missing 299 dependency files.

**Comment by Vinc3r** [comment]
This batch script is a nice idea, is it Bash command?

**Comment by arc-webservices** [comment]
Some contributors didn't properly link their textures so the batch of files they sent to my team were missing textures that were still on the contributor's computer. I've been going through each model to update them to modern formats and noticed this many times. Unfortunately, some of the contributors no longer work with NASA so the chance of getting these missing textures is small.
