### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mjhorvath** [nasa/NASA-3D-Resources#17]
I'm assuming this stuff is public domain, but please state so somewhere on the front page. Thanks.

**Comment by betalars** [comment]
> [No need to](https://en.wikipedia.org/wiki/Category:NASA_images).

I am a bit confused, the [Nasa Multimedia Guidelines](https://www.nasa.gov/multimedia/guidelines/index.html) seem to be contradicting this and they are linked here ... it's a bit weird, I don't know, if they want me to use it or not ...

**Comment by ldo** [comment]
Quote:

> NASA content - images, audio, video, and computer files used in the rendition of 3-dimensional models, such as texture maps and polygon data in any format - generally are not subject to copyright in the United States.

and

> The NASA Insignia (the blue "meatball" logo), the NASA Logotype (the "worm" logo) and the NASA Seal may not be used for any purpose without explicit permission.

Not clear enough? The material is in the public domain, trademarks are not.

**Comment by arc-webservices** [comment]
Thank you for the explanation, @ldo!
