### ISSUE TITLE
What's the unit or scale of this model?

### ISSUE THREAD

**Issue by FennexFox** [nasa/NASA-3D-Resources#19]
I want to make a model out of this model, but not sure what's the unit or scale of this.
When I open it with Blender and measure its width, it says a number of 81, which doesn't seem like meter nor feet.

**Comment by ldo** [comment]
Which model?

**Comment by FennexFox** [comment]
Mobile Launcher Platform, and/or Crawler Transporter if those two are not same scale

**Comment by ldo** [comment]
Yeah, I had a look at the Crawler Transporter, and the width of the main body is something like 4 Blender Units, which doesn’t match up with any reasonable measurement scale.

This is the point where you go to look at [Wikipedia](https://en.wikipedia.org/wiki/Crawler-transporter), which has some more exact dimensions.
