### ISSUE TITLE
Is it possible for me to fork individual models and upload a revision to make available on your website?

### ISSUE THREAD

**Issue by NIH3Dprint** [nasa/NASA-3D-Resources#2]

**Comment by projecttiles** [comment]
I was just thinking the same thing. I had to run this through netfabb Basic to fix the non-manifold edges

**Comment by sej7278** [comment]
Thinking the same, I had to run the Hubble hatch cover through meshlab to remove the awful supports which A) won't print and B) aren't needed and C) are worse than most slicers could do

**Comment by swdgit** [comment]
If they accept pull requests then I’d take that route. Especially since this issue has been open for 2 years.

**Comment by sej7278** [comment]
looking at the commits, they're all by one person and there are no PR's, guess i'll forget it

**Comment by arc-webservices** [comment]
Hello! "arc-webservices" is a generic account shared amongst various maintainers.

If you'd like to fix broken aspects of a model I suggest you issue a pull request with the goal of adding or adjusting a Blender file with its assets packed. That format would allow me to export the model to previewable formats like GLB or STL and allay concerns from directors about security concerns from the public.
