### ISSUE TITLE
[project request] - interesting AI project - fft impulse response into 3d model

### ISSUE THREAD

**Issue by ghost** [nasa/NASA-3D-Resources#26]
#### [project request] - interesting AI project - fft impulse response into 3d model

it would be interesting to:

- sample a fft impulse response consisting of:
 - conversion from áudio domain into fft domain of things like:
   - electromagnetic spectrums
   - sounds
   - visual spectrums

the process is simple:
- conversion of signals into cartesian and polar coordinates
- modelling behaviour of interesting devices
- optimizing the model with ai and permutation of value tables
- testing
- optimzing
- repeating the process

Porsche already used that for cars, and so do probably audi and bosch, but it would be amazing to see it done for nasa 3d models, if you guys are not already doing it

**Comment by arc-webservices** [comment]
This is something you should contact engineers with 😉 This repository is just an archive.
