### ISSUE TITLE
Polygon data unit/scale of the Bennu asteroid 

### ISSUE THREAD

**Issue by Fahime1991** [nasa/NASA-3D-Resources#28]
Dear all,
I downloaded your 3D **Bennu Radar.obj** of Bennu asteroid to use this polygon data. Actually, the coordinate of vertices have very small values and it cause some trouble in the other calculation.
Would you help me to know more about edge coordinates unit (**'m' or 'km' unit or scale size**?)?
If I can know in anyway, please let me know.

**Comment by arc-webservices** [comment]
Hello Fahime, the author of this model is [Michael C. Nolan](mailto:morton@orex.lpl.arizona.edu). You will need to email them to ask for more information.
