### ISSUE TITLE
A few missing files...

### ISSUE THREAD

**Issue by japreja** [nasa/NASA-3D-Resources#3]
Hello,
I have Forked the resources and cloned localy.  I was looking for SSO-3DS folder/Model that I have based my models after but could not find it in the resources.  The files is on [NASA 3D Resources website](http://nasa3d.arc.nasa.gov/detail/sso-3ds).  I made an attempt to contact DigitalSpace Corporation to see if they wouldn't mind if I uploaded it here on github, I have not heard from them as of yet.

**Comment by ldo** [comment]
I think the model has been included now--it’s in the “`3D Models/Space Shuttle Orbiter`” subdirectory.
