### ISSUE TITLE
Flawed rotations in ISS (IGOAL) model

### ISSUE THREAD

**Issue by marsfan** [nasa/NASA-3D-Resources#31]
Some of the components in the ISS (IGOAL) model are not properly rotated. Examples include the entire JEM, and the handrails on the ends of the Columbus Module. Below shows how a number of the modules are highly rotated. 

![image](https://user-images.githubusercontent.com/9311953/87190555-4d027880-c2b8-11ea-80df-72556878c5ee.png)

**Comment by arc-webservices** [comment]
This model just got an update from the original team. :) Check it out. Maybe the rotation has been fixed.
