### ISSUE TITLE
Suggest adding image of completed print to M2020 Rover

### ISSUE THREAD

**Issue by jesse-grimes-york** [nasa/NASA-3D-Resources#32]
M2020 Rover model: 
I suggest adding an image of the full assembly so that users can see what the finished product looks like. CAD image is fine, photo of print is better. Assembly instructions give a preview of the look of the model, but leave me wanting more. 

Looks to be a great model! looking forward to printing it.

**Comment by arc-webservices** [comment]
I see that there are some assembly pictures. I agree that a full assembly picture would be helpful. You'll need to contact the original model authors to get more information:

Brandon Summers Jet Propulsion Laboratory, California Institute of Technology
[Hector Ramirez](mailto:hector.r.ramirez@jpl.nasa.gov) Jet Propulsion Laboratory, California Institute of Technology
