### ISSUE TITLE
M2020-Model-Rover-STLs512020 Missing Piece

### ISSUE THREAD

**Issue by gheticle** [nasa/NASA-3D-Resources#33]
On the M2020-Model-Rover-STLs512020 model, the piece which sits between the chassis and the rsa lower mast (the lower half of the hinge) is missing from the ZIP file.

**Comment by brenagwynn** [comment]
Hey, I also noticed that part was missing. Try this one, I've quickly put it together in Fusion 360: [https://github.com/brenagwynn/NASA_Perseverance_Fixed/blob/master/rsm_base_v2.stl](https://github.com/brenagwynn/NASA_Perseverance_Fixed/blob/master/rsm_base_v2.stl)
 It may not be an exact replica, but hey, it works, at least for me for now.

**Comment by rovermeyer** [comment]
Thanks, I was about ready to design this myself.
