### ISSUE TITLE
Error Loading Perseverance.glb VALUE_NOT_IN_RANGE

### ISSUE THREAD

**Issue by Jalict** [nasa/NASA-3D-Resources#35]
Currently 1 glTF validation error for `NASA-3D-Resources/3D Models/perseverance-GLB/GLB/Perseverance.glb`

Here is the error reported by [Khronos glTF Validator](http://github.khronos.org/glTF-Validator/)
```JSON
{
    "code": "VALUE_NOT_IN_RANGE",
    "message": "Value 1.0000001192092896 is out of range.",
    "severity": 0,
    "pointer": "/materials/36/pbrMetallicRoughness/baseColorFactor"
},
```

We discovered the error while trying to import the 3D model into both our own solution and Windows 3D Viewer. Neither could load the file.

**Comment by arc-webservices** [comment]
Thank you for reporting. I have exported the glb file from its Blender source and replaced the current file.
