### ISSUE TITLE
Space in directory leads to clone/checkout errors on windows

### ISSUE THREAD

**Issue by mgreter** [nasa/NASA-3D-Resources#4]
Hello, I just tried to clone the repository and got the following error (I use tortoisegit, didn't try console directly, but I guess the space should not be there anyway):

`error: unable to create file 3D Models/CloudSat /Cloudsat.fbx (No such file or directory)`
`fatal: cannot create directory at '3D Models/CloudSat /__MACOSX': No such file or directory`

Problem is the space in/after `CloudSat `.
I guess the `__MACOSX` folders could also be removed!?
Thank you and have a nice day!

**Comment by thomthom** [comment]
Ran into this error myself trying to clone it.

**Comment by ldo** [comment]
Both “`CloudSat`” and “`CloudSat `” directories have identical copies of the file “Cloudsat.fbx”. The latter also has the useless “`__MACOSX`” directory. I think the latter can be deleted.

**Comment by arc-webservices** [comment]
The folder names causing problems with cloning have been fixed.
