### ISSUE TITLE
Duplicated Geometry In LEM Model

### ISSUE THREAD

**Issue by ldo** [nasa/NASA-3D-Resources#7]
Just been doing some work with the file “`3D Models/Apollo Lunar Module/lunarlandernofoil_carbajal.3ds`”, and I have discovered that the geometry for the main part of the legs on the descent stage has been put in twice.

**Comment by ldo** [comment]
Further to the above, I came across two little bumps on either side of the concavity above the ingress/egress hatch, which have some extra spurious geometry--whole sets of extra vertices, located well off to the side of the whole LM assembly. May be worth deleting these.

**Comment by ldo** [comment]
Ah--checking [further docs](https://www.hq.nasa.gov/alsj/alsj-LMdocs.html), it turns out those are the docking lights (on either side of the tracking light).

**Comment by arc-webservices** [comment]
Unfortunately, we no longer have contact with this model's author.
