### ISSUE TITLE
[PATCH] remove duplicated models

### ISSUE THREAD

**Issue by ldo** [nasa/NASA-3D-Resources#9]
There are quite a few duplicated files. Some make sense (e.g. textures), others don’t seem to. Enclosed are some patches to remove the obvious unneeded ones.

[ldo-remove-duplicates.zip](https://github.com/nasa/NASA-3D-Resources/files/504129/ldo-remove-duplicates.zip)

**Comment by ldo** [comment]
“`3D Models/Shuttle Parts (High Res)`” is a partial duplicate of “`3D Models/Shuttle Parts (HIgh Res)`”, but has the more sensible name. So it makes sense to get rid of the former and rename the latter to the former.

This is quite a large patch--GitHub wouldn’t let me upload it as one file. So I had to break it into eight segments. Rejoin them with a command like

    cat part-*.txt >patch.txt

As a check, the `sha256sum` of the reconstructed file should be `ae9fb35b0e044ae57d08e76e7d4797377c256f6b2f8d3175831e0a159b4f4f9a`.

[part-aa.txt](https://github.com/nasa/NASA-3D-Resources/files/504166/part-aa.txt)
[part-ab.txt](https://github.com/nasa/NASA-3D-Resources/files/504167/part-ab.txt)
[part-ac.txt](https://github.com/nasa/NASA-3D-Resources/files/504168/part-ac.txt)
[part-ad.txt](https://github.com/nasa/NASA-3D-Resources/files/504169/part-ad.txt)
[part-ae.txt](https://github.com/nasa/NASA-3D-Resources/files/504172/part-ae.txt)
[part-af.txt](https://github.com/nasa/NASA-3D-Resources/files/504176/part-af.txt)
[part-ag.txt](https://github.com/nasa/NASA-3D-Resources/files/504177/part-ag.txt)
[part-ah.txt](https://github.com/nasa/NASA-3D-Resources/files/504179/part-ah.txt)

**Comment by ldo** [comment]
Another duplicated model.

[0010-Remove-duplicate-of-3D-Models-Shuttle-Model-2.patch.txt](https://github.com/nasa/NASA-3D-Resources/files/504214/0010-Remove-duplicate-of-3D-Models-Shuttle-Model-2.patch.txt)

**Comment by ldo** [comment]
Updated patches:

[part-aa.txt](https://github.com/nasa/NASA-3D-Resources/files/1374270/part-aa.txt)
[part-ab.txt](https://github.com/nasa/NASA-3D-Resources/files/1374271/part-ab.txt)
[part-ac.txt](https://github.com/nasa/NASA-3D-Resources/files/1374272/part-ac.txt)
[part-ad.txt](https://github.com/nasa/NASA-3D-Resources/files/1374273/part-ad.txt)
[part-ae.txt](https://github.com/nasa/NASA-3D-Resources/files/1374274/part-ae.txt)
[part-af.txt](https://github.com/nasa/NASA-3D-Resources/files/1374275/part-af.txt)
[part-ag.txt](https://github.com/nasa/NASA-3D-Resources/files/1374276/part-ag.txt)
[part-ah.txt](https://github.com/nasa/NASA-3D-Resources/files/1374278/part-ah.txt)

`sha256sum` of reconstructed file should be `e1884d23b701014b6e50377a8c944c4a85d4ad5bf451bc57fe059eac122eb7a0`.

Also:
[0005-Remove-duplicate-of-3D-Models-Shuttle-Model-2.patch.txt](https://github.com/nasa/NASA-3D-Resources/files/1374291/0005-Remove-duplicate-of-3D-Models-Shuttle-Model-2.patch.txt)

**Comment by arc-webservices** [comment]
You are right! I've been finding duplicate files and removing them. I have to go through each manually so I won't be able to make use of your patches, but I really appreciate that you put the time into contributing. 🤗
